# title: Johnmark Kibui
# description: Data Scientist | Passionate about using data-driven solutions to solve real-world challenges.
# logo: Images/2825 B-W.jpg
# theme: jekyll-theme-minimal
# email: johnmarkkibui@gmail.com


# Site settings
title: "Johnmark Kibui"
description: "Data Scientist | Passionate about solving real-world problems with data."
logo: "assets/images/profile.jpg"
favicon: "assets/images/favicon.ico"
url: "https://mark-kibui.github.io"  # Update with your actual domain/GH Pages URL

# Theme Configuration (pinned to last Jekyll 3.x compatible version)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

# Author Information
author:
  name: "Johnmark Kibui"
  avatar: "assets/images/profile.jpg"
  bio: "Data Scientist | Machine Learning | AI Enthusiast"
  location: "Nairobi, Kenya"
  email: "johnmarkkibui@gmail.com"
  github: "mark-kibui"
  twitter: "johnmark_kibui"
  linkedin: "johnmark-kibui"
  stackoverflow: "your_user_id"  # Optional
  mastodon:  # Optional
    - username: "your_username"
      instance: "your_instance.social"

# Navigation Menu
header_pages:
  - about.md
  - projects.md
  - blog.md
  - contact.md

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache  # Required for include_cached tag polyfill

# Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      comments: false
      share: true
      related: false
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      comments: true
      share: true
      related: true

# Social Media Links (Theme-compatible format)
social:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mark-kibui"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/johnmark-kibui"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:johnmarkkibui@gmail.com"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/johnmark_kibui"

# Footer Settings
footer:
  show_powered_by: false
  show_repo: true  # Shows "View repository" link if set
  repo_url: "https://github.com/mark-kibui/Data_Science_Portfolio"

# Pagination (for blog posts)
paginate: 5
paginate_path: "/blog/page:num/"

# Optional Commenting (Disable if not using)
comments:
  provider: "disqus"  # Change to "utterances" for GitHub-based comments
  disqus:
    shortname: "your-disqus-shortname"

# Optional Search
search: true
search_full_content: true

# Optional Breadcrumbs
breadcrumbs: true

# Optional Table of Contents
toc: true
toc_label: "Table of Contents"
toc_icon: "fas fa-list"

# Optional Analytics (Uncomment when ready)
# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-XXXXXXX-X"
#     anonymize_ip: true
