# title: Johnmark Kibui
# description: Data Scientist | Passionate about using data-driven solutions to solve real-world challenges.
# logo: Images/2825 B-W.jpg
# theme: jekyll-theme-minimal
# email: johnmarkkibui@gmail.com


# Site settings
title: "Johnmark Kibui"
description: "Data Scientist | Passionate about solving real-world problems with data."
logo: "assets/images/Selfie- Profile_Photo.jpg"  # Ensure this image exists in the path
favicon: "assets/images/favicon.ico"  # Ensure this file exists

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast" # Other options: dark, neon, solarized, etc.

# Author Information
author:
  name: "Johnmark Kibui"
  avatar: "assets/images/profile.jpg"
  bio: "Data Scientist | Machine Learning | AI Enthusiast"
  location: "Nairobi, Kenya"
  email: "johnmarkkibui@gmail.com"
  github: "mark-kibui"
  twitter: "johnmark_kibui"  # Updated with actual handle
  linkedin: "johnmark-kibui"  # Updated with actual handle

# Navigation Menu
header_pages:
  - about.md
  - projects.md
  - blog.md
  - contact.md

# Removed sidebar section (theme handles sidebar through author_profile)
# Minimal Mistakes uses author_profile: true in front matter/defaults instead

# Footer Links
footer:
  show_powered_by: false  # Verify theme license requirements
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mark-kibui"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/johnmark-kibui"  # Updated URL
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:johnmarkkibui@gmail.com"

# Plugins (Ensure these are in Gemfile)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown Processing
markdown: kramdown
highlighter: rouge
paginate: 5

# Defaults for Pages & Posts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true  # This controls the sidebar appearance
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

# Social Media Sharing (Theme-preferred format)
social:
  name: "Johnmark Kibui"
  links:
    - icon: "fab fa-github"
      url: "https://github.com/mark-kibui"
    - icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/johnmark-kibui"
    - icon: "fas fa-envelope"
      url: "mailto:johnmarkkibui@gmail.com"

# Google Analytics (Uncomment when ready)
# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"  # Replace with actual ID
#     anonymize_ip: true  # Recommended for GDPR compliance
