title: Johnmark Kibui
description: Data Scientist | Passionate about using data-driven solutions to solve real-world challenges.
logo: /images
theme: jekyll-theme-minimal
github_username: mark-kibui
email: johnmarkkibui@gmail.com
