title: Johnmark Kibui
description: Data Scientist | Passionate about using data-driven solutions to solve real-world challenges.
logo: Images/Selfie- Profile_Photo.jpg
theme: jekyll-theme-minimal
email: johnmarkkibui@gmail.com
